name 'cabot'
maintainer 'Rafael Fonseca'
maintainer_email 'rafael.magu@gmail.com'
license 'MIT'
description 'Installs and configures Cabot'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '1.0.0'

depends 'build-essential'
depends 'git'
depends 'nginx'
depends 'nodejs'
depends 'npm'
depends 'python'
depends 'redis'
depends 'ubuntu'
